Error if RELEASE_LOG_KEY is not set

diff --git a/raiselog b/raiselog
--- a/raiselog
+++ b/raiselog
@@ -54,6 +54,11 @@ shift $((OPTIND-1))
 echo
     echo "Creating Release Log.."
 
+if [ -z "$RELEASE_LOG_KEY" ]; then
+   >&2 echo "RELEASE_LOG_KEY was not defined. Exiting."
+   exit 1
+fi
+
 if [ ! -z "${s}" ]; then
     echo "System code specified: ${s}"
 	RESULT=$(curl -sb -f --raw https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$CIRCLE_BUILD_NUM?circle-token=$CIRCLE_API_KEY | curl -sb -f -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header "x-api-key: $RELEASE_LOG_KEY" -d @- https://cr-api.in.ft.com/v2/circleci?systemCode=${s})
@@ -63,7 +68,7 @@ else
 fi
 
 if [[ "${RESULT}" == *"error"* ]] || [[ "${RESULT}" == *"Forbidden"* ]]; then
-    echo "Error : ${RESULT}"
+    >&2 echo "Error : ${RESULT}"
     exit 1
 fi
 
