Error if KONSTRUCTOR_REGISTRY_KEY is unset

diff --git a/register_service b/register_service
--- a/register_service
+++ b/register_service
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 set -e
 
 usage() {
@@ -45,7 +45,12 @@ shift $((OPTIND-1))
 
 
 if [ ! -f "${f}" ]; then
-   echo "No file specified. Exiting."
+   >&2 echo "No file specified. Exiting."
+   exit 1
+fi
+
+if [ -z "$KONSTRUCTOR_REGISTRY_KEY" ]; then
+   >&2 echo "KONSTRUCTOR_REGISTRY_KEY was not defined. Exiting."
    exit 1
 fi
 
@@ -56,7 +61,7 @@ echo "Konstructor Service being registered.  File : ${f}"
 RESULT=$(curl -sb -f -X POST https://registry-api.in.ft.com/v1/register -d @${f} --header "Content-Type: application/json" --header "x-api-key: $KONSTRUCTOR_REGISTRY_KEY")
 
 if [[ "${RESULT}" == *"error"* ]] || [[ "${RESULT}" == *"Forbidden"* ]]; then
-    echo "Error : ${RESULT}"
+    >&2 echo "Error : ${RESULT}"
     exit 1
 fi
 
